version: '3.8'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/Frontend
      - /Frontend/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

networks:
  my-bridge-network:
    driver: bridge